[selene]
base = "roblox"
name = "WoS"



[[GetPartFromPort.args]]
type = "number"
[[GetPartFromPort.args]]
required = false
type = "string"

[[GetPartsFromPort.args]]
type = "number"

[[GetPort.args]]
type = "number"

[[TriggerPort.args]]
type = "number"

[[Beep.args]]
type = "number"

[[JSONDecode.args]]
type = "string"

[[JSONEncode.args]]
type = "any"